SQLLite DB with ChinookDB

< Create chinook.db in same directory as this notebook >

# Create Filename.db from sql database script in text format

In [7]:
import sqlite3

# Database file name
db_file = 'Chinook_cache.db'
# SQL script file name
sql_file = '/content/sample_data/Chinook_Sqlite.sql' #here I want to link path in a different folder

try:
    # Read the SQL script
    with open(sql_file, 'r') as f:
        sql_script = f.read()

    # Connect to the database (creates it if it doesn't exist)
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    # Execute the SQL script
    cursor.executescript(sql_script)

    conn.commit()
    print(f"Database '{db_file}' created successfully from '{sql_file}'.")

except FileNotFoundError:
    print(f"Error: SQL script file '{sql_file}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    if 'conn' in locals() and conn:
        conn.close()

Database 'Chinook_cache.db' created successfully from '/content/sample_data/Chinook_Sqlite.sql'.

## Test

In [8]:
# List all Tables Names
import sqlite3
conn = sqlite3.connect('Chinook_cache.db')
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Tables in the database:")
for table in tables:
    print(table[0])

conn.close()

Tables in the database:
Album
Artist
Customer
Employee
Genre
Invoice
InvoiceLine
MediaType
Playlist
PlaylistTrack
Track

In [10]:
import sqlite3
conn = sqlite3.connect('Chinook_cache.db') # Replace with your filename
cursor = conn.cursor()
# Example: Execute a simple query
cursor.execute("SELECT * FROM Genre") # Replace 'your_table'
results = cursor.fetchall()
for row in results:
    print(row)
conn.close()

(1, 'Rock')
(2, 'Jazz')
(3, 'Metal')
(4, 'Alternative & Punk')
(5, 'Rock And Roll')
(6, 'Blues')
(7, 'Latin')
(8, 'Reggae')
(9, 'Pop')
(10, 'Soundtrack')
(11, 'Bossa Nova')
(12, 'Easy Listening')
(13, 'Heavy Metal')
(14, 'R&B/Soul')
(15, 'Electronica/Dance')
(16, 'World')
(17, 'Hip Hop/Rap')
(18, 'Science Fiction')
(19, 'TV Shows')
(20, 'Sci Fi & Fantasy')
(21, 'Drama')
(22, 'Comedy')
(23, 'Alternative')
(24, 'Classical')
(25, 'Opera')